version: '3.9'
services:
  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/conf/:/etc/nginx/conf.d/:rw
      - ${PWD}/certbot/www:/var/www/certbot/:rw
    restart: always
    
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ${PWD}/certbot/www/:/var/www/certbot/:rw
      - ${PWD}/certbot/conf/:/etc/letsencrypt/:rw
